/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aktywa.*;
import bledy.BrakSurowcaDoWylosowania;
import bledy.BrakWalutDoWylosowania;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import org.jdesktop.observablecollections.ObservableList;
import projekt.Swiat;

/**
 *
 * @author Monika Zielińska
 */
public class PanelAktywa extends javax.swing.JPanel {
    
    private ObservableList<Aktywa> aktywa;
    
    
    /**
     * Creates new form OknoAktywa
     */
    public PanelAktywa() {
        this.aktywa = Swiat.listaAktywa; 
        initComponents();
        informacjePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dodajSurowiecPrzycisk = new javax.swing.JButton();
        dodajWalutaPrzycisk = new javax.swing.JButton();
        listaAktywaScrollPane = new javax.swing.JScrollPane();
        aktywaList = new javax.swing.JList<>();
        listaAktywaLabel = new javax.swing.JLabel();
        informacjePanel = new javax.swing.JPanel();
        informacjeLabel = new javax.swing.JLabel();
        nazwaTextField = new javax.swing.JTextField();
        wartoscAktualnaTextField = new javax.swing.JTextField();
        nazwaLabel = new javax.swing.JLabel();
        wartoscAktualnaLabel = new javax.swing.JLabel();
        rodzajLabel = new javax.swing.JLabel();
        rodzajTextField = new javax.swing.JTextField();
        rynekLabel = new javax.swing.JLabel();
        rynekTextField = new javax.swing.JTextField();
        usunSurowiecButton = new javax.swing.JButton();
        wartoscMinTextField = new javax.swing.JTextField();
        wartoscMinLabel = new javax.swing.JLabel();
        wartoscMaxTextField = new javax.swing.JTextField();
        wartoscMaxLabel = new javax.swing.JLabel();
        akcjePanel = new javax.swing.JPanel();
        iloscLabel = new javax.swing.JLabel();
        iloscTextField = new javax.swing.JTextField();
        iloscDostepnaLabel = new javax.swing.JLabel();
        iloscDostepnaTextField = new javax.swing.JTextField();
        wykresButton = new javax.swing.JButton();
        wykresWieleButton = new javax.swing.JButton();
        surowiecPanel = new javax.swing.JPanel();
        jednostkaLabel = new javax.swing.JLabel();
        jednostkaTextField = new javax.swing.JTextField();
        walutaLabel = new javax.swing.JLabel();
        walutaTextField = new javax.swing.JTextField();
        walutaPanel = new javax.swing.JPanel();
        listaKrajowLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        krajeWalutyList = new javax.swing.JList<>();

        dodajSurowiecPrzycisk.setText("Dodaj surowiec");
        dodajSurowiecPrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajSurowiecPrzyciskActionPerformed(evt);
            }
        });

        dodajWalutaPrzycisk.setText("Dodaj walutę");
        dodajWalutaPrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajWalutaPrzyciskActionPerformed(evt);
            }
        });

        aktywaList.setInheritsPopupMenu(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${aktywa}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, aktywaList);
        bindingGroup.addBinding(jListBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aktywo}"), aktywaList, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        aktywaList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                aktywaListValueChanged(evt);
            }
        });
        listaAktywaScrollPane.setViewportView(aktywaList);

        listaAktywaLabel.setText("Wybierz aktywa:");

        informacjeLabel.setText("Informacje i edycja:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aktywo.nazwa}"), nazwaTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        wartoscAktualnaTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aktywo.wartoscAktualna}"), wartoscAktualnaTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nazwaLabel.setText("Nazwa:");

        wartoscAktualnaLabel.setText("Aktualna wartość:");

        rodzajLabel.setText("Rodzaj:");

        rodzajTextField.setEditable(false);
        rodzajTextField.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aktywo.klasa}"), rodzajTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        rynekLabel.setText("Rynek:");

        rynekTextField.setEditable(false);
        rynekTextField.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aktywo.rynek.nazwa}"), rynekTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        usunSurowiecButton.setText("Usuń surowiec");
        usunSurowiecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunSurowiecButtonActionPerformed(evt);
            }
        });

        wartoscMinTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aktywo.wartoscMin}"), wartoscMinTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        wartoscMinLabel.setText("Min. wartość:");

        wartoscMaxTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aktywo.wartoscMax}"), wartoscMaxTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        wartoscMaxLabel.setText("Max. wartość:");

        iloscLabel.setText("Ilość:");

        iloscTextField.setEditable(false);

        iloscDostepnaLabel.setText("Dostępna ilość:");

        iloscDostepnaTextField.setEditable(false);

        javax.swing.GroupLayout akcjePanelLayout = new javax.swing.GroupLayout(akcjePanel);
        akcjePanel.setLayout(akcjePanelLayout);
        akcjePanelLayout.setHorizontalGroup(
            akcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(akcjePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(akcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iloscLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iloscDostepnaLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(akcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iloscTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(iloscDostepnaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap())
        );
        akcjePanelLayout.setVerticalGroup(
            akcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(akcjePanelLayout.createSequentialGroup()
                .addGroup(akcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iloscLabel)
                    .addComponent(iloscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(akcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iloscDostepnaLabel)
                    .addComponent(iloscDostepnaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        wykresButton.setText("Wyrysuj wykres");
        wykresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wykresButtonActionPerformed(evt);
            }
        });

        wykresWieleButton.setText("Wyrysuj wykres wielu aktyw");
        wykresWieleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wykresWieleButtonActionPerformed(evt);
            }
        });

        jednostkaLabel.setText("Jednostka:");

        jednostkaTextField.setEditable(false);

        walutaLabel.setText("Waluta:");

        walutaTextField.setEditable(false);

        javax.swing.GroupLayout surowiecPanelLayout = new javax.swing.GroupLayout(surowiecPanel);
        surowiecPanel.setLayout(surowiecPanelLayout);
        surowiecPanelLayout.setHorizontalGroup(
            surowiecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surowiecPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(surowiecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(surowiecPanelLayout.createSequentialGroup()
                        .addComponent(jednostkaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jednostkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(surowiecPanelLayout.createSequentialGroup()
                        .addComponent(walutaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(walutaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        surowiecPanelLayout.setVerticalGroup(
            surowiecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surowiecPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(surowiecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jednostkaLabel)
                    .addComponent(jednostkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(surowiecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walutaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walutaLabel))
                .addGap(0, 0, 0))
        );

        listaKrajowLabel.setText("Lista krajów, w której jest środkiem płatniczym:");

        jScrollPane1.setViewportView(krajeWalutyList);

        javax.swing.GroupLayout walutaPanelLayout = new javax.swing.GroupLayout(walutaPanel);
        walutaPanel.setLayout(walutaPanelLayout);
        walutaPanelLayout.setHorizontalGroup(
            walutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walutaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(walutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(walutaPanelLayout.createSequentialGroup()
                        .addComponent(listaKrajowLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        walutaPanelLayout.setVerticalGroup(
            walutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walutaPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(listaKrajowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout informacjePanelLayout = new javax.swing.GroupLayout(informacjePanel);
        informacjePanel.setLayout(informacjePanelLayout);
        informacjePanelLayout.setHorizontalGroup(
            informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(akcjePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacjePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(wykresWieleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wykresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usunSurowiecButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addComponent(surowiecPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(informacjePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rodzajLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazwaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rynekLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rodzajTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(nazwaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(rynekTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addComponent(wartoscMaxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wartoscMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addComponent(wartoscMinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wartoscMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addComponent(wartoscAktualnaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(wartoscAktualnaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addComponent(informacjeLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(walutaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        informacjePanelLayout.setVerticalGroup(
            informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacjePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacjeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rodzajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rodzajLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rynekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rynekLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwaLabel))
                .addGap(6, 6, 6)
                .addComponent(surowiecPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(akcjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wartoscAktualnaLabel)
                    .addComponent(wartoscAktualnaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wartoscMinLabel)
                    .addComponent(wartoscMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wartoscMaxLabel)
                    .addComponent(wartoscMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(walutaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(usunSurowiecButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wykresButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wykresWieleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaAktywaLabel)
                    .addComponent(listaAktywaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dodajSurowiecPrzycisk, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(dodajWalutaPrzycisk, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(informacjePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaAktywaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaAktywaScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dodajSurowiecPrzycisk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dodajWalutaPrzycisk)
                .addGap(30, 30, 30))
            .addComponent(informacjePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajSurowiecPrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajSurowiecPrzyciskActionPerformed
        try {
            Swiat.stworzSurowiec();
        } catch (BrakSurowcaDoWylosowania ex) {
            System.err.println("Nie można stworzyć nowego surowca, brak możliwej nazwy dla kolejnego surowca");
        }
        aktywaList.setSelectedIndex(aktywaList.getModel().getSize()-1);
    }//GEN-LAST:event_dodajSurowiecPrzyciskActionPerformed

    private void dodajWalutaPrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajWalutaPrzyciskActionPerformed
        try {
            Swiat.stworzWaluta();
            aktywaList.setSelectedIndex(aktywaList.getModel().getSize()-1);
        } catch (BrakWalutDoWylosowania ex) {
            System.err.println("Nie można stworzyć nowej waluty, brak możliwej nazwy dla kolejnej waluty.");
        }
    }//GEN-LAST:event_dodajWalutaPrzyciskActionPerformed

    private void usunSurowiecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunSurowiecButtonActionPerformed
        if(aktywaList.getSelectedIndex() == -1) return;
        Swiat.rynekSurowcow.usunSurowiec((Surowiec) aktywo);
    }//GEN-LAST:event_usunSurowiecButtonActionPerformed

    private void aktywaListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_aktywaListValueChanged
        informacjePanel.setVisible(false);
        if(aktywaList.getSelectedIndex() == -1) return;
        informacjePanel.setVisible(true);
        usunSurowiecButton.setVisible(false);
        akcjePanel.setVisible(false);
        surowiecPanel.setVisible(false);
        walutaPanel.setVisible(false);
        if(aktywo.getClass() == Surowiec.class) {
            Surowiec surowiec = (Surowiec) aktywo;
            usunSurowiecButton.setVisible(true);
            surowiecPanel.setVisible(true);
            jednostkaTextField.setText(surowiec.getJednostka());
            walutaTextField.setText(surowiec.getWaluta().getNazwa());
        }
        else if(aktywo.getClass() == Akcja.class) {
            Akcja akcja = (Akcja) aktywo;
            iloscDostepnaTextField.setText(Integer.toString(akcja.getDostepnaIlosc()));
            iloscTextField.setText(Integer.toString(akcja.getIlosc()));
            akcjePanel.setVisible(true);
        }
        else if(aktywo.getClass() == Waluta.class) {
            Waluta waluta = (Waluta) aktywo;
            walutaPanel.setVisible(true);
            DefaultListModel listModel = new DefaultListModel();
            for (String kraj : waluta.getListaKrajowWaluty()) {
                listModel.addElement(kraj);
            }
            krajeWalutyList.setModel(listModel);
        }
    }//GEN-LAST:event_aktywaListValueChanged

    Wykres wykres = null;
    
    private void wykresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wykresButtonActionPerformed
        if(aktywaList.getSelectedIndex() == -1) return;
        if(aktywo.getListaWartosci().isEmpty() ) return;
        if((wykres != null) && wykres.isVisible()) wykres.dispose();
        
        wykres = new Wykres(aktywo);
        wykres.setVisible(true);
        
    }//GEN-LAST:event_wykresButtonActionPerformed

    private void wykresWieleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wykresWieleButtonActionPerformed
        if(aktywaList.getSelectedIndex() == -1) return;
        if(aktywo.getListaWartosci().isEmpty() ) return;
        if((wykres != null) && wykres.isVisible()) wykres.dispose();
        
        List <Aktywa> listaZaznaczonych = new ArrayList<>();
        for(int index : aktywaList.getSelectedIndices()) {
            listaZaznaczonych.add(aktywa.get(index));
        }
        
        wykres = new Wykres(listaZaznaczonych);
        wykres.setVisible(true);
    }//GEN-LAST:event_wykresWieleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel akcjePanel;
    private javax.swing.JList<String> aktywaList;
    private javax.swing.JButton dodajSurowiecPrzycisk;
    private javax.swing.JButton dodajWalutaPrzycisk;
    private javax.swing.JLabel iloscDostepnaLabel;
    private javax.swing.JTextField iloscDostepnaTextField;
    private javax.swing.JLabel iloscLabel;
    private javax.swing.JTextField iloscTextField;
    private javax.swing.JLabel informacjeLabel;
    private javax.swing.JPanel informacjePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jednostkaLabel;
    private javax.swing.JTextField jednostkaTextField;
    private javax.swing.JList<String> krajeWalutyList;
    private javax.swing.JLabel listaAktywaLabel;
    private javax.swing.JScrollPane listaAktywaScrollPane;
    private javax.swing.JLabel listaKrajowLabel;
    private javax.swing.JLabel nazwaLabel;
    private javax.swing.JTextField nazwaTextField;
    private javax.swing.JLabel rodzajLabel;
    private javax.swing.JTextField rodzajTextField;
    private javax.swing.JLabel rynekLabel;
    private javax.swing.JTextField rynekTextField;
    private javax.swing.JPanel surowiecPanel;
    private javax.swing.JButton usunSurowiecButton;
    private javax.swing.JLabel walutaLabel;
    private javax.swing.JPanel walutaPanel;
    private javax.swing.JTextField walutaTextField;
    private javax.swing.JLabel wartoscAktualnaLabel;
    private javax.swing.JTextField wartoscAktualnaTextField;
    private javax.swing.JLabel wartoscMaxLabel;
    private javax.swing.JTextField wartoscMaxTextField;
    private javax.swing.JLabel wartoscMinLabel;
    private javax.swing.JTextField wartoscMinTextField;
    private javax.swing.JButton wykresButton;
    private javax.swing.JButton wykresWieleButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public ObservableList<Aktywa> getAktywa() {
        return aktywa;
    }

    /**
     *
     * @param aktywa
     */
    public void setAktywa(ObservableList<Aktywa> aktywa) {
        this.aktywa = aktywa;
    }
    
    
    private Aktywa aktywo;

    /**
     *
     */
    public static final String PROP_AKTYWO = "aktywo";

    /**
     * Get the value of aktywo
     *
     * @return the value of aktywo
     */
    public Aktywa getAktywo() {
        return aktywo;
    }

    /**
     * Set the value of aktywo
     *
     * @param aktywo new value of aktywo
     */
    public void setAktywo(Aktywa aktywo) {
        Aktywa oldAktywo = this.aktywo;
        this.aktywo = aktywo;
        firePropertyChange(PROP_AKTYWO, oldAktywo, aktywo);
    }
    
}
