/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aktywa.Akcja;
import javax.swing.DefaultListModel;
import org.jdesktop.observablecollections.ObservableList;
import projekt.Indeks;
import projekt.Swiat;
import rynki.*;

/**
 *
 * @author Monika Zielińska
 */
public class PanelRynki extends javax.swing.JPanel {
    
    private ObservableList<Rynek> rynki;
    
    /**
     * Creates new form OknoAktywa
     */
    public PanelRynki() {
        this.rynki = Swiat.listaRynkow;
        initComponents();
        informacjePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dodajGieldaPrzycisk = new javax.swing.JButton();
        listaRynkiScrollPane = new javax.swing.JScrollPane();
        rynkiList = new javax.swing.JList<>();
        listaRynkiLabel = new javax.swing.JLabel();
        informacjePanel = new javax.swing.JPanel();
        informacjeLabel = new javax.swing.JLabel();
        marzaTextField = new javax.swing.JTextField();
        nazwaTextField = new javax.swing.JTextField();
        nazwaLabel = new javax.swing.JLabel();
        marzaLabel = new javax.swing.JLabel();
        gieldaPanel = new javax.swing.JPanel();
        walutaTextField = new javax.swing.JTextField();
        walutaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        spolkiIndeksuList = new javax.swing.JList<>();
        indeksWybierzComboBox = new javax.swing.JComboBox<>();
        indeksDodajPrzycisk = new javax.swing.JButton();
        indeksWartoscTextField = new javax.swing.JTextField();
        usunIndeksButton = new javax.swing.JButton();
        indeksWartoscLabel = new javax.swing.JLabel();
        adresTextField = new javax.swing.JTextField();
        zawartoscRynkuScrollPane = new javax.swing.JScrollPane();
        zawartoscRynkuList = new javax.swing.JList<>();
        zawartoscRynkuLabel = new javax.swing.JLabel();

        dodajGieldaPrzycisk.setText("Dodaj giełdę");
        dodajGieldaPrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajGieldaPrzyciskActionPerformed(evt);
            }
        });

        rynkiList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rynkiList.setInheritsPopupMenu(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${rynki}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, rynkiList);
        bindingGroup.addBinding(jListBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${rynek}"), rynkiList, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        rynkiList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                rynkiListValueChanged(evt);
            }
        });
        listaRynkiScrollPane.setViewportView(rynkiList);

        listaRynkiLabel.setText("Wybierz rynek:");

        informacjeLabel.setText("Informacje i edycja:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${rynek.marza}"), marzaTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nazwaTextField.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${rynek.nazwa}"), nazwaTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nazwaLabel.setText("Nazwa:");

        marzaLabel.setText("Marża [%]:");

        walutaTextField.setEditable(false);

        walutaLabel.setText("Waluta:");

        jScrollPane1.setViewportView(spolkiIndeksuList);

        indeksWybierzComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indeksWybierzComboBoxActionPerformed(evt);
            }
        });

        indeksDodajPrzycisk.setText("Dodaj indeks");
        indeksDodajPrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indeksDodajPrzyciskActionPerformed(evt);
            }
        });

        indeksWartoscTextField.setEditable(false);

        usunIndeksButton.setText("Usuń indeks");
        usunIndeksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunIndeksButtonActionPerformed(evt);
            }
        });

        indeksWartoscLabel.setText("Wartość indeksu:");

        adresTextField.setEditable(false);

        javax.swing.GroupLayout gieldaPanelLayout = new javax.swing.GroupLayout(gieldaPanel);
        gieldaPanel.setLayout(gieldaPanelLayout);
        gieldaPanelLayout.setHorizontalGroup(
            gieldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(gieldaPanelLayout.createSequentialGroup()
                .addGroup(gieldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gieldaPanelLayout.createSequentialGroup()
                        .addComponent(indeksDodajPrzycisk, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usunIndeksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gieldaPanelLayout.createSequentialGroup()
                        .addComponent(walutaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(walutaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gieldaPanelLayout.createSequentialGroup()
                        .addComponent(indeksWybierzComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(indeksWartoscLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(indeksWartoscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adresTextField))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gieldaPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {indeksDodajPrzycisk, usunIndeksButton});

        gieldaPanelLayout.setVerticalGroup(
            gieldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gieldaPanelLayout.createSequentialGroup()
                .addGroup(gieldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walutaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walutaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(gieldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indeksWybierzComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indeksWartoscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indeksWartoscLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gieldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indeksDodajPrzycisk)
                    .addComponent(usunIndeksButton))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gieldaPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {indeksDodajPrzycisk, usunIndeksButton});

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${rynek.listaAktywRynku}");
        jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, zawartoscRynkuList);
        bindingGroup.addBinding(jListBinding);

        zawartoscRynkuScrollPane.setViewportView(zawartoscRynkuList);

        zawartoscRynkuLabel.setText("Lista dostępnych aktywów:");

        javax.swing.GroupLayout informacjePanelLayout = new javax.swing.GroupLayout(informacjePanel);
        informacjePanel.setLayout(informacjePanelLayout);
        informacjePanelLayout.setHorizontalGroup(
            informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacjePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacjePanelLayout.createSequentialGroup()
                                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nazwaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marzaLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(marzaTextField)
                                    .addComponent(nazwaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(informacjePanelLayout.createSequentialGroup()
                                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zawartoscRynkuLabel)
                                    .addComponent(gieldaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(zawartoscRynkuScrollPane))
                                .addGap(31, 31, 31))))
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addComponent(informacjeLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        informacjePanelLayout.setVerticalGroup(
            informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacjePanelLayout.createSequentialGroup()
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addComponent(informacjeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nazwaLabel)
                        .addGap(11, 11, 11)
                        .addComponent(marzaLabel)
                        .addGap(13, 13, 13))
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addComponent(nazwaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marzaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(gieldaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zawartoscRynkuLabel)
                .addGap(3, 3, 3)
                .addComponent(zawartoscRynkuScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaRynkiLabel)
                    .addComponent(listaRynkiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dodajGieldaPrzycisk, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(informacjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(informacjePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaRynkiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaRynkiScrollPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodajGieldaPrzycisk)))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajGieldaPrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajGieldaPrzyciskActionPerformed
        Swiat.stworzGielda();
        rynkiList.setSelectedIndex(rynkiList.getModel().getSize()-1);
    }//GEN-LAST:event_dodajGieldaPrzyciskActionPerformed

    private void rynkiListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_rynkiListValueChanged
        if(rynkiList.getSelectedIndex() != -1) {
            informacjePanel.setVisible(true);
            gieldaPanel.setVisible(false);
            if(rynek.getClass() == Gielda.class) {
                Gielda g = (Gielda) rynek;
                gieldaPanel.setVisible(true);
                walutaTextField.setText(g.getWaluta().getNazwa());
                adresTextField.setText(g.getAdresSiedziby()+", "+g.getMiasto()+", "+g.getKraj());
                indeksWybierzComboBox.removeAllItems();
                spolkiIndeksuList.setModel(new DefaultListModel<>());
                indeksWartoscTextField.setText("");
                for (Indeks ind : g.getListaIndeksow()) {
                    indeksWybierzComboBox.addItem(ind.getNazwaIndeksu());
                }
            }
        }
    }//GEN-LAST:event_rynkiListValueChanged

    private void indeksDodajPrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indeksDodajPrzyciskActionPerformed
        Gielda g = (Gielda) rynek;
        Indeks ind = Swiat.stworzIndeks(g);
        indeksWybierzComboBox.addItem(ind.getNazwaIndeksu());
        indeksWybierzComboBox.repaint();
    }//GEN-LAST:event_indeksDodajPrzyciskActionPerformed

    private void indeksWybierzComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indeksWybierzComboBoxActionPerformed
        int nr = indeksWybierzComboBox.getSelectedIndex();
        if(nr == -1) {
            DefaultListModel listModel = new DefaultListModel(); 
            spolkiIndeksuList.setModel(listModel);
            return;
        }
        Gielda g = (Gielda) rynek;
        Indeks ind = g.getListaIndeksow().get(nr);
        ind.aktualizujIndeks();
        DefaultListModel listModel = new DefaultListModel(); 
        for (Akcja akcja : ind.getListaAkcji()) {
            listModel.addElement(akcja.getSpolka());
        }
        spolkiIndeksuList.setModel(listModel);
        indeksWartoscTextField.setText(Double.toString(ind.getWartoscIndeksu()));
    }//GEN-LAST:event_indeksWybierzComboBoxActionPerformed

    private void usunIndeksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunIndeksButtonActionPerformed
        int nr = indeksWybierzComboBox.getSelectedIndex();
        Gielda g = (Gielda) rynek;
        g.getListaIndeksow().remove(nr);
        indeksWybierzComboBox.removeItemAt(nr);
        
    }//GEN-LAST:event_usunIndeksButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresTextField;
    private javax.swing.JButton dodajGieldaPrzycisk;
    private javax.swing.JPanel gieldaPanel;
    private javax.swing.JButton indeksDodajPrzycisk;
    private javax.swing.JLabel indeksWartoscLabel;
    private javax.swing.JTextField indeksWartoscTextField;
    private javax.swing.JComboBox<String> indeksWybierzComboBox;
    private javax.swing.JLabel informacjeLabel;
    private javax.swing.JPanel informacjePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listaRynkiLabel;
    private javax.swing.JScrollPane listaRynkiScrollPane;
    private javax.swing.JLabel marzaLabel;
    private javax.swing.JTextField marzaTextField;
    private javax.swing.JLabel nazwaLabel;
    private javax.swing.JTextField nazwaTextField;
    private javax.swing.JList<String> rynkiList;
    private javax.swing.JList<String> spolkiIndeksuList;
    private javax.swing.JButton usunIndeksButton;
    private javax.swing.JLabel walutaLabel;
    private javax.swing.JTextField walutaTextField;
    private javax.swing.JLabel zawartoscRynkuLabel;
    private javax.swing.JList<String> zawartoscRynkuList;
    private javax.swing.JScrollPane zawartoscRynkuScrollPane;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return lista rynków
     */
    public ObservableList<Rynek> getRynki() {
        return rynki;
    }

    /**
     *
     * @param rynki
     */
    public void setRynki(ObservableList<Rynek> rynki) {
        this.rynki = rynki;
    }

        private Rynek rynek;

    /**
     *
     */
    public static final String PROP_RYNEK = "rynek";

    /**
     * Get the value of rynek
     *
     * @return the value of rynek
     */
    public Rynek getRynek() {
        return rynek;
    }

    /**
     * Set the value of rynek
     *
     * @param rynek new value of rynek
     */
    public void setRynek(Rynek rynek) {
        Rynek oldRynek = this.rynek;
        this.rynek = rynek;
        firePropertyChange(PROP_RYNEK, oldRynek, rynek);
    }




    
    
    
}
