/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import org.jdesktop.observablecollections.ObservableList;
import projekt.Swiat;
import projekt.Spolka;

/**
 *
 * @author Monika Zielińska
 */
public class PanelSpolki extends javax.swing.JPanel {
    
    private ObservableList<Spolka> spolki;
    
    /**
     * Creates new form OknoAktywa
     */
    public PanelSpolki() {
        this.spolki = Swiat.listaSpolek;
        initComponents();
        informacjePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dodajSpolkaPrzycisk = new javax.swing.JButton();
        listaSpolkiScrollPane = new javax.swing.JScrollPane();
        spolkiList = new javax.swing.JList<>();
        listaSpolkiLabel = new javax.swing.JLabel();
        informacjePanel = new javax.swing.JPanel();
        informacjeLabel = new javax.swing.JLabel();
        nazwaTextField = new javax.swing.JTextField();
        iloscTextField = new javax.swing.JTextField();
        kursAktualnyTextField = new javax.swing.JTextField();
        nazwaLabel = new javax.swing.JLabel();
        iloscAkcjiLabel = new javax.swing.JLabel();
        kursAktualnyLabel = new javax.swing.JLabel();
        dataWycenyLabel = new javax.swing.JLabel();
        dataWycenyTextField = new javax.swing.JTextField();
        kursMinLabel = new javax.swing.JLabel();
        kursMinTextField = new javax.swing.JTextField();
        kursMaxTextField = new javax.swing.JTextField();
        kursMaxLabel = new javax.swing.JLabel();
        kursOtwarciaTextField = new javax.swing.JTextField();
        kursOtwarciaLabel = new javax.swing.JLabel();
        kursMaxLabel1 = new javax.swing.JLabel();
        kapitalWlasnyTextField = new javax.swing.JTextField();
        kapitalZakladowyLabel = new javax.swing.JLabel();
        kapitalZakladowyTextField = new javax.swing.JTextField();
        obrotyLabel = new javax.swing.JLabel();
        obrotyTextField = new javax.swing.JTextField();
        wolumenTextField = new javax.swing.JTextField();
        wolumenLabel = new javax.swing.JLabel();
        przychodLabel = new javax.swing.JLabel();
        przychodTextField = new javax.swing.JTextField();
        zyskLabel = new javax.swing.JLabel();
        zyskTextField = new javax.swing.JTextField();
        usunSpolkaPrzycisk = new javax.swing.JButton();
        wykupAkcjePrzycisk = new javax.swing.JButton();

        dodajSpolkaPrzycisk.setText("Dodaj spółkę");
        dodajSpolkaPrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajSpolkaPrzyciskActionPerformed(evt);
            }
        });

        spolkiList.setInheritsPopupMenu(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${spolki}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, spolkiList);
        bindingGroup.addBinding(jListBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka}"), spolkiList, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        spolkiList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                spolkiListValueChanged(evt);
            }
        });
        listaSpolkiScrollPane.setViewportView(spolkiList);

        listaSpolkiLabel.setText("Wybierz spółkę:");

        informacjeLabel.setText("Informacje i edycja:");

        nazwaTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.nazwa}"), nazwaTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        iloscTextField.setEditable(false);
        iloscTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.akcjeSpolki.ilosc}"), iloscTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        kursAktualnyTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.akcjeSpolki.wartoscAktualna}"), kursAktualnyTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nazwaLabel.setText("Nazwa:");

        iloscAkcjiLabel.setText("Ilość akcji:");

        kursAktualnyLabel.setText("Aktualny kurs:");

        dataWycenyLabel.setText("Data wyceny:");

        dataWycenyTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.dataWyceny}"), dataWycenyTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        kursMinLabel.setText("Min. kurs:");

        kursMinTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.akcjeSpolki.wartoscMin}"), kursMinTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        kursMaxTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.akcjeSpolki.wartoscMax}"), kursMaxTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        kursMaxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursMaxTextFieldActionPerformed(evt);
            }
        });

        kursMaxLabel.setText("Max. kurs:");

        kursOtwarciaTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.kursOtwarcia}"), kursOtwarciaTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        kursOtwarciaLabel.setText("Kurs otwarcia:");

        kursMaxLabel1.setText("Kapitał własny:");

        kapitalWlasnyTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.kapitalWlasny}"), kapitalWlasnyTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        kapitalWlasnyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapitalWlasnyTextFieldActionPerformed(evt);
            }
        });

        kapitalZakladowyLabel.setText("Kapitał zakładowy:");

        kapitalZakladowyTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.kapitalZakladowy}"), kapitalZakladowyTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        kapitalZakladowyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapitalZakladowyTextFieldActionPerformed(evt);
            }
        });

        obrotyLabel.setText("Obroty:");

        obrotyTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.obroty}"), obrotyTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        obrotyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrotyTextFieldActionPerformed(evt);
            }
        });

        wolumenTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.wolumen}"), wolumenTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        wolumenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wolumenTextFieldActionPerformed(evt);
            }
        });

        wolumenLabel.setText("Wolumen:");

        przychodLabel.setText("Przychód:");

        przychodTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.przychod}"), przychodTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        przychodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przychodTextFieldActionPerformed(evt);
            }
        });

        zyskLabel.setText("Zysk:");

        zyskTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${spolka.zysk}"), zyskTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        zyskTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zyskTextFieldActionPerformed(evt);
            }
        });

        usunSpolkaPrzycisk.setText("Usuń spółkę");
        usunSpolkaPrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunSpolkaPrzyciskActionPerformed(evt);
            }
        });

        wykupAkcjePrzycisk.setText("Wykup akcje");
        wykupAkcjePrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wykupAkcjePrzyciskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout informacjePanelLayout = new javax.swing.GroupLayout(informacjePanel);
        informacjePanel.setLayout(informacjePanelLayout);
        informacjePanelLayout.setHorizontalGroup(
            informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacjePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacjeLabel)
                    .addGroup(informacjePanelLayout.createSequentialGroup()
                        .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nazwaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursAktualnyLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iloscAkcjiLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataWycenyLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursMinLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursMaxLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursOtwarciaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursMaxLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kapitalZakladowyLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obrotyLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wolumenLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(przychodLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zyskLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50)
                        .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(kursAktualnyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iloscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataWycenyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kursMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kursMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kursOtwarciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kapitalWlasnyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kapitalZakladowyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(obrotyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(wolumenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(przychodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zyskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nazwaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(usunSpolkaPrzycisk, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wykupAkcjePrzycisk, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        informacjePanelLayout.setVerticalGroup(
            informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacjePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacjeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iloscAkcjiLabel)
                    .addComponent(iloscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataWycenyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataWycenyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursOtwarciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursOtwarciaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursAktualnyLabel)
                    .addComponent(kursAktualnyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursMinLabel)
                    .addComponent(kursMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursMaxLabel)
                    .addComponent(kursMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursMaxLabel1)
                    .addComponent(kapitalWlasnyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kapitalZakladowyLabel)
                    .addComponent(kapitalZakladowyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obrotyLabel)
                    .addComponent(obrotyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wolumenLabel)
                    .addComponent(wolumenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przychodLabel)
                    .addComponent(przychodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zyskLabel)
                    .addComponent(zyskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wykupAkcjePrzycisk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usunSpolkaPrzycisk)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaSpolkiLabel)
                    .addComponent(listaSpolkiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dodajSpolkaPrzycisk, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(informacjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaSpolkiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaSpolkiScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dodajSpolkaPrzycisk)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addComponent(informacjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajSpolkaPrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajSpolkaPrzyciskActionPerformed
        Swiat.stworzSpolka();
        spolkiList.setSelectedIndex(spolkiList.getModel().getSize()-1);
    }//GEN-LAST:event_dodajSpolkaPrzyciskActionPerformed

    private void usunSpolkaPrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunSpolkaPrzyciskActionPerformed
        if(spolkiList.getSelectedIndex() == -1) return;
        spolka.usun();
        usunSpolkaPrzycisk.setEnabled(false);
    }//GEN-LAST:event_usunSpolkaPrzyciskActionPerformed

    private void kursMaxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursMaxTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kursMaxTextFieldActionPerformed

    private void kapitalWlasnyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapitalWlasnyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kapitalWlasnyTextFieldActionPerformed

    private void kapitalZakladowyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapitalZakladowyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kapitalZakladowyTextFieldActionPerformed

    private void obrotyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrotyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obrotyTextFieldActionPerformed

    private void wolumenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wolumenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wolumenTextFieldActionPerformed

    private void przychodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przychodTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_przychodTextFieldActionPerformed

    private void zyskTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zyskTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zyskTextFieldActionPerformed

    private void spolkiListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_spolkiListValueChanged
        informacjePanel.setVisible(false);
        if(spolkiList.getSelectedIndex() != -1) {
            informacjePanel.setVisible(true);
            setSize(getPreferredSize());
        }
    }//GEN-LAST:event_spolkiListValueChanged

    private void wykupAkcjePrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wykupAkcjePrzyciskActionPerformed
        spolka.wykupAkcje();
        
    }//GEN-LAST:event_wykupAkcjePrzyciskActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataWycenyLabel;
    private javax.swing.JTextField dataWycenyTextField;
    private javax.swing.JButton dodajSpolkaPrzycisk;
    private javax.swing.JLabel iloscAkcjiLabel;
    private javax.swing.JTextField iloscTextField;
    private javax.swing.JLabel informacjeLabel;
    private javax.swing.JPanel informacjePanel;
    private javax.swing.JTextField kapitalWlasnyTextField;
    private javax.swing.JLabel kapitalZakladowyLabel;
    private javax.swing.JTextField kapitalZakladowyTextField;
    private javax.swing.JLabel kursAktualnyLabel;
    private javax.swing.JTextField kursAktualnyTextField;
    private javax.swing.JLabel kursMaxLabel;
    private javax.swing.JLabel kursMaxLabel1;
    private javax.swing.JTextField kursMaxTextField;
    private javax.swing.JLabel kursMinLabel;
    private javax.swing.JTextField kursMinTextField;
    private javax.swing.JLabel kursOtwarciaLabel;
    private javax.swing.JTextField kursOtwarciaTextField;
    private javax.swing.JLabel listaSpolkiLabel;
    private javax.swing.JScrollPane listaSpolkiScrollPane;
    private javax.swing.JLabel nazwaLabel;
    private javax.swing.JTextField nazwaTextField;
    private javax.swing.JLabel obrotyLabel;
    private javax.swing.JTextField obrotyTextField;
    private javax.swing.JLabel przychodLabel;
    private javax.swing.JTextField przychodTextField;
    private javax.swing.JList<String> spolkiList;
    private javax.swing.JButton usunSpolkaPrzycisk;
    private javax.swing.JLabel wolumenLabel;
    private javax.swing.JTextField wolumenTextField;
    private javax.swing.JButton wykupAkcjePrzycisk;
    private javax.swing.JLabel zyskLabel;
    private javax.swing.JTextField zyskTextField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public ObservableList<Spolka> getSpolki() {
        return spolki;
    }

    /**
     *
     * @param spolki
     */
    public void setSpolki(ObservableList<Spolka> spolki) {
        this.spolki = spolki;
    }
    
        private Spolka spolka;

    /**
     *
     */
    public static final String PROP_SPOLKA = "spolka";

    /**
     * Get the value of spolka
     *
     * @return the value of spolka
     */
    public Spolka getSpolka() {
        return spolka;
    }

    /**
     * Set the value of spolka
     *
     * @param spolka new value of spolka
     */
    public void setSpolka(Spolka spolka) {
        Spolka oldSpolka = this.spolka;
        this.spolka = spolka;
        firePropertyChange(PROP_SPOLKA, oldSpolka, spolka);
    }




    
    
    
}
